# 애플리케이션 설정 파일

spring:
  datasource:
    url: jdbc:mysql://eum-db.czay0iku081t.eu-north-1.rds.amazonaws.com/eumdb
    username: admin
    password: fraidy53$$
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create    # update에서 create로 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: leeah03200320@gmail.com
    password: tfzj rewn avpx mtyg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379


server:
  port: 8081 
